"use client";

import { useEffect, useState } from "react";

import { ApiError, api } from "../../lib/api";

type Case = { id: string; public_id: string; status: string; severity: string; queue: string; assigned_moderator_id: string | null };
type Detail = { public_id: string; status: string; severity: string; priority: number; queue: string; target_type: string; report_count: number; notes: { id: string; body: string }[]; actions: { id: string; type: string; reason: string }[]; safe_evidence: { id: string; source_type: string; safe_reference: string | null }[] };

export default function ModerationPage() {
  const [cases, setCases] = useState<Case[]>([]); const [detail, setDetail] = useState<Detail | null>(null); const [selectedId, setSelectedId] = useState(""); const [note, setNote] = useState(""); const [assignee, setAssignee] = useState(""); const [action, setAction] = useState("contain_content"); const [targetId, setTargetId] = useState(""); const [reason, setReason] = useState(""); const [error, setError] = useState("");
  useEffect(() => { api<Case[]>("/trust-safety/cases").then(setCases).catch((e) => setError(e instanceof ApiError ? e.message : "Unable to load moderation cases")); }, []);
  const load = (id: string) => api<Detail>(`/trust-safety/cases/${id}`).then((value) => { setSelectedId(id); setDetail(value); }).catch((e) => setError(e instanceof ApiError ? e.message : "Unable to load case"));
  const addNote = () => api(`/trust-safety/cases/${selectedId}/notes`, { method: "POST", body: JSON.stringify({ body: note }) }).then(() => { setNote(""); return load(selectedId); }).catch((e) => setError(e instanceof ApiError ? e.message : "Unable to add note"));
  const assign = () => api(`/trust-safety/cases/${selectedId}/assign`, { method: "POST", body: JSON.stringify({ moderator_id: assignee || null }) }).then(() => load(selectedId)).catch((e) => setError(e instanceof ApiError ? e.message : "Unable to assign case"));
  const enforce = () => api(`/trust-safety/cases/${selectedId}/enforcement`, { method: "POST", body: JSON.stringify({ action, target_id: targetId, reason }) }).then(() => { setReason(""); return load(selectedId); }).catch((e) => setError(e instanceof ApiError ? e.message : "Unable to enforce case"));
  return <section className="card"><p className="eyebrow">TRUST & SAFETY</p><h1>Moderation queue</h1><p>Case access and actions are authorized by the server.</p>{error && <p className="error">{error}</p>}<ul>{cases.map((item) => <li key={item.id}><button type="button" onClick={() => void load(item.id)}><strong>{item.public_id}</strong> — {item.severity} · {item.queue} · {item.status}</button></li>)}</ul>{detail && <article><h2>{detail.public_id}</h2><p>{detail.severity} · priority {detail.priority} · {detail.queue} · {detail.status}</p><p>Target: {detail.target_type} · Reports: {detail.report_count}</p><label>Assign moderator ID<input value={assignee} onChange={(e) => setAssignee(e.target.value)} /></label><button type="button" onClick={() => void assign()}>Assign</button><h3>Enforcement</h3><select value={action} onChange={(e) => setAction(e.target.value)}><option value="contain_content">Contain content</option><option value="suspend_creator">Suspend creator</option><option value="suspend_marketplace">Suspend marketplace selling</option><option value="terminate_live">Terminate live</option><option value="disable_featuring">Disable featuring</option></select><input aria-label="Enforcement target ID" value={targetId} onChange={(e) => setTargetId(e.target.value)} /><input aria-label="Enforcement reason" value={reason} onChange={(e) => setReason(e.target.value)} /><button type="button" disabled={!targetId || !reason.trim()} onClick={() => void enforce()}>Apply enforcement</button><h3>Safe evidence</h3><ul>{detail.safe_evidence.map((item) => <li key={item.id}>{item.source_type}{item.safe_reference ? " · reference available" : ""}</li>)}</ul><h3>Notes</h3><ul>{detail.notes.map((item) => <li key={item.id}>{item.body}</li>)}</ul><label>Add case note<textarea value={note} onChange={(e) => setNote(e.target.value)} /></label><button type="button" disabled={!note.trim()} onClick={() => void addNote()}>Add note</button><h3>Actions</h3><ul>{detail.actions.map((item) => <li key={item.id}>{item.type} · {item.reason}</li>)}</ul></article>}{!error && !cases.length && <p>No accessible cases.</p>}</section>;
}
