"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

import styles from "../../../components/operations-workspace.module.css";
import { ApiError, api } from "../../../lib/api";

type Verification = { registered: boolean; identity_status: string | null; age_status: string | null };
type Item = { id: string; status: string; release_type: string; creator: string; participant: string; content_titles: string[]; has_evidence: boolean; performer_verification: Verification; created_at: string };
type Detail = { id: string; status: string; creator: { display_name: string; username: string }; release_type: string; participant: string; contents: { id: string; title: string; type: string }[]; has_evidence: boolean; evidence_reference: string | null; performer_verification: Verification; created_at: string; allowed_decisions: string[]; audit: { type: string; created_at: string }[] };

export default function ModeratorConsentPage() {
  const [items, setItems] = useState<Item[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const pageSize = 25; const [status, setStatus] = useState("pending"); const [search, setSearch] = useState(""); const [selected, setSelected] = useState<Detail | null>(null); const [approved, setApproved] = useState(true); const [reason, setReason] = useState(""); const [confirmed, setConfirmed] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { const params = new URLSearchParams({ page: String(page), page_size: String(pageSize) }); if (status) params.set("status", status); if (search) params.set("search", search); try { const result = await api<{ items: Item[]; total: number }>(`/trust-safety/consent/operations?${params}`); setItems(result.items); setTotal(result.total); setError(""); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to load consent reviews."); } }, [page, search, status]);
  useEffect(() => { void load(); }, [load]);
  const open = async (id: string) => { try { setSelected(await api<Detail>(`/trust-safety/consent/operations/${id}`)); setReason(""); setConfirmed(false); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to open consent review."); } };
  const filter = (event: FormEvent) => { event.preventDefault(); setPage(1); void load(); };
  const decide = async () => { if (!selected) return; try { await api(`/trust-safety/consent/operations/${selected.id}/decision`, { method: "POST", body: JSON.stringify({ approved, reason }) }); setNotice("Consent decision recorded and creator notified."); await open(selected.id); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to decide consent review."); } };
  return <main className={styles.page}><header className={styles.hero}><p className="eyebrow">TRUST &amp; SAFETY OPERATIONS</p><h1>Consent review</h1><p>Review creator-owned context. Sensitive evidence is only returned to separately authorised reviewers.</p></header><section className={styles.panel}><form className={styles.filters} onSubmit={filter}><label>Creator or participant<input value={search} onChange={(e) => setSearch(e.target.value)} /></label><label>Status<select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All</option>{["pending", "verified", "rejected", "revoked", "expired"].map((value) => <option key={value}>{value}</option>)}</select></label><button>Apply filters</button></form>{error && <p className={styles.error} role="alert">{error}</p>}{notice && <p className={styles.notice} role="status">{notice}</p>}<div className={styles.split}><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Creator / participant</th><th>Content</th><th>Evidence</th><th>Identity / age</th><th>Status</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><button className={styles.rowButton} onClick={() => void open(item.id)}><strong>{item.creator}</strong><span>{item.participant}</span></button></td><td>{item.content_titles.join(", ") || "—"}</td><td>{item.has_evidence ? "Submitted" : "None"}</td><td>{item.performer_verification.identity_status ?? "—"} / {item.performer_verification.age_status ?? "—"}</td><td><span className={styles.status}>{item.status}</span></td></tr>)}</tbody></table>{!items.length && <p className={styles.empty}>No releases match these filters.</p>}<div className={styles.pagination}><button disabled={page === 1} onClick={() => setPage((value) => value - 1)}>Previous</button><span>Page {page}</span><button disabled={page * pageSize >= total} onClick={() => setPage((value) => value + 1)}>Next</button></div></div>
      <aside className={`${styles.panel} ${styles.detail}`}>{selected ? <><div className={styles.detailHeader}><div><p className="eyebrow">RELEASE DETAIL</p><h2>{selected.participant}</h2></div><span className={styles.status}>{selected.status}</span></div><dl className={styles.facts}><div><dt>Creator</dt><dd>{selected.creator.display_name || selected.creator.username}</dd></div><div><dt>Release type</dt><dd>{selected.release_type.replaceAll("_", " ")}</dd></div><div><dt>Content</dt><dd>{selected.contents.map((content) => content.title).join(", ")}</dd></div><div><dt>Evidence</dt><dd>{selected.has_evidence ? (selected.evidence_reference ?? "Restricted to sensitive-evidence reviewers") : "Not submitted"}</dd></div><div><dt>Performer identity</dt><dd>{selected.performer_verification.identity_status ?? (selected.performer_verification.registered ? "Not verified" : "No matching registered performer")}</dd></div><div><dt>Age assurance</dt><dd>{selected.performer_verification.age_status ?? "Not verified"}</dd></div></dl>{selected.allowed_decisions.length > 0 && <div className={styles.decision}><label>Decision<select value={String(approved)} onChange={(e) => setApproved(e.target.value === "true")}><option value="true">Verify</option><option value="false">Reject</option></select></label><label>Reason<textarea value={reason} onChange={(e) => setReason(e.target.value)} /></label><label className={styles.confirm}><input checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} type="checkbox" /> I confirm this review outcome.</label><button disabled={!confirmed || reason.trim().length < 8} onClick={() => void decide()}>Record decision</button></div>}<h3>Audit history</h3><ul className={styles.timeline}>{selected.audit.map((event, index) => <li key={`${event.type}-${index}`}>{event.type}<small>{new Date(event.created_at).toLocaleString()}</small></li>)}</ul></> : <p className={styles.empty}>Select a release to inspect it.</p>}</aside></div></section></main>;
}
