"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

import { ApiError, api } from "../lib/api";
import styles from "./operations-workspace.module.css";

type KycItem = { verification_id: string; creator: { display_name: string; username: string; email: string; application_status: string }; provider: string; provider_reference: string; status: string; country_code: string | null; started_at: string; review_category: string | null };
type KycDetail = KycItem & { verified_at: string | null; expires_at: string | null; identity_verified: boolean; adult_verified: boolean; allowed_actions: string[]; manual_approval_permitted: boolean; audit: { type: string; created_at: string }[] };

export function CreatorKycOperations() {
  const [items, setItems] = useState<KycItem[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const pageSize = 25;
  const [search, setSearch] = useState(""); const [status, setStatus] = useState("needs_review"); const [provider, setProvider] = useState(""); const [country, setCountry] = useState("");
  const [selected, setSelected] = useState<KycDetail | null>(null); const [action, setAction] = useState("request_reverification"); const [reason, setReason] = useState(""); const [confirmed, setConfirmed] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { const params = new URLSearchParams({ page: String(page), page_size: String(pageSize) }); if (search) params.set("search", search); if (status) params.set("status", status); if (provider) params.set("provider", provider); if (country) params.set("country_code", country); try { const result = await api<{ items: KycItem[]; total: number }>(`/admin/compliance/creator-kyc?${params}`); setItems(result.items); setTotal(result.total); setError(""); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to load KYC reviews."); } }, [country, page, provider, search, status]);
  useEffect(() => { void load(); }, [load]);
  const open = async (id: string) => { try { setSelected(await api<KycDetail>(`/admin/compliance/creator-kyc/${id}`)); setReason(""); setConfirmed(false); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to open KYC review."); } };
  const filter = (event: FormEvent) => { event.preventDefault(); setPage(1); void load(); };
  const decide = async () => { if (!selected) return; try { await api(`/admin/compliance/creator-kyc/${selected.verification_id}/decision`, { method: "POST", body: JSON.stringify({ action, reason, expected_status: "needs_review" }) }); setNotice("KYC review outcome recorded and the creator was notified."); await open(selected.verification_id); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to record KYC review."); } };
  return <main className={styles.page}><header className={styles.hero}><p className="eyebrow">COMPLIANCE OPERATIONS</p><h1>Creator KYC review</h1><p>Resolve provider-requested reviews without exposing identity documents or overriding provider authority.</p></header><section className={styles.panel}>
    <form className={styles.filters} onSubmit={filter}><label>Creator<input onChange={(e) => setSearch(e.target.value)} value={search} /></label><label>Status<select onChange={(e) => setStatus(e.target.value)} value={status}><option value="">All</option>{["needs_review", "pending", "failed", "verified", "expired"].map((v) => <option key={v}>{v}</option>)}</select></label><label>Provider<input onChange={(e) => setProvider(e.target.value)} value={provider} /></label><label>Country<input maxLength={2} onChange={(e) => setCountry(e.target.value.toUpperCase())} value={country} /></label><button>Apply filters</button></form>
    {error && <p className={styles.error} role="alert">{error}</p>}{notice && <p className={styles.notice} role="status">{notice}</p>}<div className={styles.split}><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Creator</th><th>Provider</th><th>Country</th><th>Status</th><th>Started</th></tr></thead><tbody>{items.map((item) => <tr key={item.verification_id}><td><button className={styles.rowButton} onClick={() => void open(item.verification_id)}><strong>{item.creator.display_name || item.creator.username}</strong><span>@{item.creator.username}</span></button></td><td>{item.provider}</td><td>{item.country_code ?? "—"}</td><td><span className={styles.status}>{item.status.replaceAll("_", " ")}</span></td><td>{new Date(item.started_at).toLocaleString()}</td></tr>)}</tbody></table>{!items.length && <p className={styles.empty}>No KYC reviews match these filters.</p>}<div className={styles.pagination}><button disabled={page === 1} onClick={() => setPage((v) => v - 1)}>Previous</button><span>Page {page}</span><button disabled={page * pageSize >= total} onClick={() => setPage((v) => v + 1)}>Next</button></div></div>
    <aside className={`${styles.panel} ${styles.detail}`}>{selected ? <><div className={styles.detailHeader}><div><p className="eyebrow">REVIEW DETAIL</p><h2>{selected.creator.display_name || selected.creator.username}</h2></div><span className={styles.status}>{selected.status.replaceAll("_", " ")}</span></div><dl className={styles.facts}><div><dt>Provider</dt><dd>{selected.provider}</dd></div><div><dt>Provider reference</dt><dd>{selected.provider_reference}</dd></div><div><dt>Country</dt><dd>{selected.country_code ?? "Not provided"}</dd></div><div><dt>Category</dt><dd>{selected.review_category ?? "Provider review"}</dd></div></dl><p>Manual approval is not permitted: verified identity and adulthood require a signed provider outcome.</p><h3>Audit history</h3><ul className={styles.timeline}>{selected.audit.map((event, index) => <li key={`${event.type}-${index}`}>{event.type}<small>{new Date(event.created_at).toLocaleString()}</small></li>)}</ul>{selected.allowed_actions.length > 0 && <div className={styles.decision}><label>Permitted action<select onChange={(e) => setAction(e.target.value)} value={action}>{selected.allowed_actions.map((v) => <option key={v} value={v}>{v.replaceAll("_", " ")}</option>)}</select></label><label>Review reason<textarea onChange={(e) => setReason(e.target.value)} value={reason} /></label><label className={styles.confirm}><input checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} type="checkbox" /> I confirm this audited outcome.</label><button disabled={!confirmed || reason.trim().length < 8} onClick={() => void decide()}>Record review outcome</button></div>}</> : <p className={styles.empty}>Select a creator verification to inspect it.</p>}</aside></div>
  </section></main>;
}
