"use client";

import { FormEvent, useEffect, useState } from "react";

import { ApiError, api } from "../lib/api";

type Price = { id: string; target_type: string; duration_seconds: number; amount_minor: number; currency: string; version: number };
type Slot = { id: string; slot_key: string; position: number; active: boolean; prices: Price[] };
type Surface = { id: string; kind: string; status: string; slots: Slot[] };
type Target = { target_type: string; target_id: string; title: string };
type Booking = { id: string; status: string; starts_at: string; ends_at: string; price_minor: number; currency: string; payment_attempt_id: string | null; purchaser_user_id: string; actor_user_id: string };

export function FeaturingDashboard({ manager = false }: { manager?: boolean }) {
  const [inventory, setInventory] = useState<Surface[]>([]); const [targets, setTargets] = useState<Target[]>([]); const [bookings, setBookings] = useState<Booking[]>([]); const [message, setMessage] = useState("");
  const refresh = async () => { const [surfaces, availableTargets, history] = await Promise.all([api<Surface[]>("/featuring/inventory"), api<Target[]>("/featuring/eligible-targets"), api<Booking[]>("/featuring/bookings/mine")]); setInventory(surfaces); setTargets(availableTargets); setBookings(history); };
  useEffect(() => { refresh().catch((error: unknown) => setMessage(error instanceof ApiError ? error.message : "Unable to load featuring")); }, []);
  async function book(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { const row = await api<Booking>("/featuring/bookings", { method: "POST", headers: { "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ slot_id: form.get("slot_id"), target_type: form.get("target_type"), target_id: form.get("target_id"), starts_at: new Date(String(form.get("starts_at"))).toISOString(), duration_seconds: Number(form.get("duration_seconds")), ...(manager && form.get("payer_user_id") ? { payer_user_id: form.get("payer_user_id") } : {}) }) }); setMessage(`Booking created at server price. Selected payer must authorize payment.${row.purchaser_user_id ? "" : ""}`); await refresh(); } catch (error) { setMessage(error instanceof ApiError ? error.message : "Booking could not be created"); } }
  async function pay(id: string) { try { const result = await api<{ payment_attempt_id: string }>(`/featuring/bookings/${id}/payment`, { method: "POST" }); setMessage(`Payment authorization created: ${result.payment_attempt_id}`); await refresh(); } catch (error) { setMessage(error instanceof ApiError ? error.message : "Only the selected payer can authorize this booking"); } }
  const prices = inventory.flatMap(surface => surface.slots.flatMap(slot => slot.prices.map(price => ({ surface, slot, price }))));
  return <section className="card"><p className="eyebrow">{manager ? "MANAGER FEATURING" : "CREATOR FEATURING"}</p><h2>Feature a public target</h2><p>Sponsored placements are visibly labelled and remain separate from organic discovery.</p><form onSubmit={book}><label>Target<select name="target_id" required>{targets.map(target => <option key={target.target_id} value={target.target_id}>{target.title} ({target.target_type})</option>)}</select></label><input type="hidden" name="target_type" value={targets[0]?.target_type ?? "creator"} /><label>Inventory / server price<select name="slot_id" required>{prices.map(({ surface, slot, price }) => <option key={price.id} value={slot.id}>{surface.kind} · {slot.slot_key} · {(price.amount_minor / 100).toFixed(2)} {price.currency} / {price.duration_seconds / 3600}h</option>)}</select></label><label>Duration (seconds; must match an offered product)<input name="duration_seconds" type="number" min="1" defaultValue={prices[0]?.price.duration_seconds ?? 3600} required /></label><label>Start (UTC)<input name="starts_at" type="datetime-local" required /></label>{manager && <label>Explicit payer user ID (leave blank to pay as manager)<input name="payer_user_id" placeholder="Creator must authorize if selected" /></label>}<button disabled={!targets.length || !prices.length}>Reserve slot</button></form><h2>Booking history</h2><ul>{bookings.map(booking => <li key={booking.id}>{booking.status} · {(booking.price_minor / 100).toFixed(2)} {booking.currency} · {new Date(booking.starts_at).toLocaleString()} {booking.status === "awaiting_payment" && <button onClick={() => void pay(booking.id)}>Authorize selected payer payment</button>}</li>)}</ul>{message && <p role="status">{message}</p>}</section>;
}
