"use client";

import { FormEvent, useEffect, useState } from "react";
import { api, ApiError } from "../lib/api";

type Asset = { id: string; status: string; media_type?: string };
type Listing = { id: string; title: string; description: string | null; category: string; condition: string; status: string; quantity_available: number; price_amount_minor: number; currency: string; shipping_mode: string; origin_country_code: string; shipping_charged_minor: number; media_asset_ids: string[] };

export function MarketplaceAuthoring({ assets }: { assets: Asset[] }) {
  const [listings, setListings] = useState<Listing[]>([]); const [editing, setEditing] = useState<Listing | null>(null); const [message, setMessage] = useState("");
  const refresh = async () => setListings(await api<Listing[]>("/marketplace/listings/mine"));
  useEffect(() => { void refresh(); }, []);
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = event.currentTarget; const data = new FormData(form);
    const payload = { title: data.get("title"), description: data.get("description") || null, category: data.get("category"), condition: data.get("condition"), quantity_available: Number(data.get("stock")), price_amount_minor: Number(data.get("price")), currency: String(data.get("currency")).toUpperCase(), shipping_mode: data.get("shipping_mode"), origin_country_code: String(data.get("origin_country")).toUpperCase(), shipping_charged_minor: Number(data.get("shipping")), media_asset_ids: data.getAll("media") };
    try { await api(editing ? `/marketplace/listings/${editing.id}` : "/marketplace/listings", { method: editing ? "PUT" : "POST", body: JSON.stringify(payload) }); setMessage(editing ? "Listing draft updated." : "Listing draft created."); setEditing(null); form.reset(); await refresh(); }
    catch (error) { setMessage(error instanceof ApiError ? error.message : "Listing could not be saved"); }
  }
  async function action(listing: Listing, action: "submit" | "deactivate") { try { await api(`/marketplace/listings/${listing.id}/${action}`, { method: "POST" }); setMessage(action === "submit" ? "Listing submitted for review." : "Listing deactivated; historical orders are unchanged."); await refresh(); } catch (error) { setMessage(error instanceof ApiError ? error.message : "Listing could not be updated"); } }
  const editable = !editing || ["draft", "paused", "rejected"].includes(editing.status);
  return <section aria-label="Marketplace authoring"><h2>Marketplace listings</h2><p>Create a physical listing draft, attach dedicated safe-public images, then submit it for review.</p>
    <form key={editing?.id ?? "new"} onSubmit={save}><label>Title<input defaultValue={editing?.title} maxLength={160} name="title" required /></label><label>Description<textarea defaultValue={editing?.description ?? ""} maxLength={5000} name="description" /></label><label>Category<input defaultValue={editing?.category} maxLength={80} name="category" required /></label><label>Condition<select defaultValue={editing?.condition ?? "new"} name="condition"><option value="new">New</option><option value="like_new">Like new</option><option value="used">Used</option><option value="personal_worn">Personal / worn</option></select></label><label>Price (minor units)<input defaultValue={editing?.price_amount_minor} min="1" name="price" required type="number" /></label><label>Currency<input defaultValue={editing?.currency ?? "EUR"} maxLength={3} minLength={3} name="currency" required /></label><label>Stock<input defaultValue={editing?.quantity_available ?? 1} min="0" name="stock" required type="number" /></label><label>Shipping reach<select defaultValue={editing?.shipping_mode ?? "domestic"} name="shipping_mode"><option value="domestic">Domestic</option><option value="selected_countries">Selected countries</option><option value="worldwide">Worldwide</option></select></label><label>Origin country<input defaultValue={editing?.origin_country_code ?? "PT"} maxLength={2} minLength={2} name="origin_country" required /></label><label>Shipping charge (minor units)<input defaultValue={editing?.shipping_charged_minor ?? 0} min="0" name="shipping" required type="number" /></label><fieldset><legend>Listing images</legend>{assets.filter((asset) => asset.status === "ready" && asset.media_type === "image").map((asset) => <label key={asset.id}><input defaultChecked={editing?.media_asset_ids.includes(asset.id)} name="media" type="checkbox" value={asset.id} />{asset.id.slice(0, 8)}</label>)}</fieldset><button disabled={!editable}>Save draft</button>{editing && <button onClick={() => setEditing(null)} type="button">Cancel edit</button>}</form>
    <ul>{listings.map((listing) => <li key={listing.id}><strong>{listing.title}</strong> · {listing.status} · {listing.quantity_available} in stock <button disabled={!['draft','paused','rejected'].includes(listing.status)} onClick={() => setEditing(listing)} type="button">Edit</button><button disabled={!['draft','paused'].includes(listing.status)} onClick={() => void action(listing, "submit")} type="button">Submit</button><button disabled={!['published','sold_out'].includes(listing.status)} onClick={() => void action(listing, "deactivate")} type="button">Deactivate</button></li>)}</ul>{message && <p role="status">{message}</p>}
  </section>;
}
