import { expect, test } from "@playwright/test";

import { expectAuthenticatedAs } from "./auth-helpers";
import { securityLink } from "./mailpit";

test("complete real authentication lifecycle", async ({ page }) => {
  const email = `e2e-${Date.now()}@example.com`;
  const old = "original-password-123";
  const fresh = "replacement-password-123";
  await page.goto("/register");
  await page.getByLabel("Email").fill(email);
  await page.getByRole("textbox", { name: /^Password\b/ }).fill(old);
  await page.getByRole("button", { name: "Create account" }).click();
  await expect(page.getByRole("heading", { name: "Verify your email" })).toBeVisible();
  const verify = await securityLink(email, "/verify-email");
  await page.goto(verify);
  await page.getByRole("button", { name: "Verify email" }).click();
  await expect(page.getByText("Email verified")).toBeVisible();
  await page.getByRole("button", { name: "Verify email" }).click();
  await expect(page.getByText("Token is invalid or expired")).toBeVisible();
  await page.goto("/login");
  await page.getByLabel("Email").fill(email);
  await page.getByRole("textbox", { name: /^Password\b/ }).fill(old);
  await page.getByRole("button", { name: "Log in" }).click();
  await expectAuthenticatedAs(page, email);
  await page.getByRole("button", { name: "Log out" }).click();
  await page.goto("/account");
  await expect(page.getByText("Authentication required")).toBeVisible();
  await page.goto("/forgot-password");
  await page.getByLabel("Email").fill(email);
  await page.getByRole("button", { name: "Send reset link" }).click();
  const reset = await securityLink(email, "/reset-password");
  await page.goto(reset);
  await page.getByLabel("New password").fill(fresh);
  await page.getByRole("button", { name: "Reset password" }).click();
  await expect(page.getByText("Password reset")).toBeVisible();
  await page.getByRole("button", { name: "Reset password" }).click();
  await expect(page.getByText("Token is invalid or expired")).toBeVisible();
  await page.goto("/login");
  await page.getByLabel("Email").fill(email);
  await page.getByRole("textbox", { name: /^Password\b/ }).fill(old);
  await page.getByRole("button", { name: "Log in" }).click();
  await expect(page.getByText("Invalid email or password")).toBeVisible();
  await page.getByRole("textbox", { name: /^Password\b/ }).fill(fresh);
  await page.getByRole("button", { name: "Log in" }).click();
  await expectAuthenticatedAs(page, email);
});
