import { expect, test, type Page } from "@playwright/test";

import { completeCreatorVerification, completeRegistrationCompliance, expectAuthenticatedAs } from "./auth-helpers";
import { securityLink } from "./mailpit";

const apiBase = process.env.E2E_API_URL ?? "http://127.0.0.1:38180";
const admin = { email: "phase2-e2e-admin@example.com", password: "phase2-e2e-admin-password" };
const image = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=", "base64");

async function api(page: Page, path: string, method = "GET", body?: unknown) {
  return page.evaluate(async ({ apiBase, path, method, body }) => {
    const response = await fetch(`${apiBase}/api/v1${path}`, { method, credentials: "include", headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined });
    return { status: response.status, body: await response.json().catch(() => null) };
  }, { apiBase, path, method, body });
}
async function login(page: Page, email: string, password: string) { await page.goto("/login"); await page.getByLabel("Email").fill(email); await page.getByRole("textbox", { name: /^Password\b/ }).fill(password); await page.getByRole("button", { name: "Log in" }).click(); await expectAuthenticatedAs(page, email); }
async function register(page: Page, email: string, password: string) { await page.goto("/register"); await completeRegistrationCompliance(page); await page.getByLabel("Email").fill(email); await page.getByRole("textbox", { name: /^Password\b/ }).fill(password); await page.getByRole("checkbox", { name: /I confirm I am at least 18/ }).check(); await page.getByRole("button", { name: "Create account" }).click(); await page.goto(await securityLink(email, "/verify-email")); await page.getByRole("button", { name: "Verify email" }).click(); await login(page, email, password); }
async function logout(page: Page) { await page.goto("/account"); await page.getByRole("button", { name: "Log out" }).click(); }
async function overflowingElements(page: Page) {
  return page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1 ? [] : [...document.querySelectorAll<HTMLElement>("body *")].filter((element) => {
    const bounds = element.getBoundingClientRect();
    return bounds.right > window.innerWidth + 1 || bounds.left < -1;
  }).map((element) => ({ tag: element.tagName, className: String(element.className), text: element.textContent?.trim().slice(0, 80) })));
}

test("browser closure: profile media, marketplace authoring, Live config, and 2-to-1 consent", async ({ browser, page }) => {
  test.setTimeout(240_000);
  const stamp = Date.now(); const password = "browser-closure-password"; const username = `closure${stamp}`; const creatorEmail = `closure-creator-${stamp}@example.com`;
  await register(page, creatorEmail, password);
  await page.getByRole("link", { name: "Become a creator" }).click(); await page.getByRole("textbox", { name: /^Your @handle/ }).fill(username); await page.getByLabel("Display name").fill("Closure Creator"); await page.getByRole("button", { name: "Save profile" }).click(); await page.getByRole("button", { name: "Submit application" }).click(); await completeCreatorVerification(page);
  await logout(page); await login(page, admin.email, admin.password); const applications = await api(page, "/admin/creator-applications"); const creator = applications.body.find((item: { username: string }) => item.username === username); expect(creator).toBeTruthy(); expect((await api(page, `/admin/creator-applications/${creator.id}/approve`, "POST")).status).toBe(200);
  await logout(page); await login(page, creatorEmail, password); await page.goto("/creator-onboarding"); await page.getByRole("checkbox", { name: "Make my approved creator profile public" }).check(); await page.getByRole("button", { name: "Save profile" }).click(); await expect.poll(async () => (await api(page, "/creators/me")).body.is_public).toBe(true);

  await page.goto("/creator-studio"); await page.getByRole("button", { name: /^Media library / }).click();
  for (const [index, name] of ["avatar.png", "cover.png", "listing.png"].entries()) { await page.locator('input[type="file"]').setInputFiles({ name, mimeType: "image/png", buffer: image }); await page.getByRole("button", { name: "Upload media" }).click(); await expect.poll(async () => ((await api(page, "/media/mine")).body as { status: string }[]).filter((asset) => asset.status === "ready").length, { timeout: 30_000 }).toBeGreaterThanOrEqual(index + 1); }
  const assets = (await api(page, "/media/mine")).body as { id: string }[];
  await logout(page); await login(page, admin.email, admin.password);
  for (const asset of assets.slice(0, 3)) { expect((await api(page, `/admin/media-assets/${asset.id}/audience`, "PUT", { audience: "safe_public" })).status).toBe(200); expect((await api(page, `/admin/media-assets/${asset.id}/moderation`, "PUT", { status: "approved", reason: "Browser closure fixture review" })).status).toBe(200); }
  await logout(page); await login(page, creatorEmail, password); await page.goto("/creator-studio"); await page.getByRole("button", { name: /^Media library / }).click();
  const profilePanel = page.getByLabel("Profile media"); await profilePanel.getByLabel("Ready image").first().selectOption(assets[0].id); await profilePanel.getByRole("button", { name: "Save avatar" }).click(); await expect(profilePanel.getByText("Avatar saved")).toBeVisible(); await profilePanel.getByLabel("Ready image").nth(1).selectOption(assets[1].id); await profilePanel.getByRole("button", { name: "Save cover" }).click(); await expect(profilePanel.getByText("Cover saved")).toBeVisible(); const profile = await api(page, `/creators/${username}`); expect(profile.body.avatar_reference).toContain("/media/profile/"); expect(profile.body.cover_reference).toContain("/media/profile/"); expect(JSON.stringify(profile.body)).not.toContain("original/"); await page.goto(`/creator/${username}`); await expect(page.getByAltText("Closure Creator profile photo")).toHaveAttribute("src", /\/media\/profile\//); await expect(page.getByAltText("Closure Creator cover")).toHaveAttribute("src", /\/media\/profile\//);
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto("/creator-studio"); await page.getByRole("button", { name: /^Media library / }).click(); await expect(page.getByLabel("Profile media")).toBeVisible(); expect(await overflowingElements(page)).toEqual([]); await page.setViewportSize({ width: 1280, height: 720 });

  await page.getByRole("button", { name: /^Business / }).click(); const market = page.getByLabel("Marketplace authoring"); await market.getByLabel("Title").fill(`Closure listing ${stamp}`); await market.getByLabel("Category").fill("collectible"); await market.getByLabel("Price (minor units)").fill("750"); await market.getByLabel("Stock").fill("2"); await market.getByLabel("Shipping charge (minor units)").fill("100"); await market.getByRole("checkbox").nth(2).check(); await market.getByRole("button", { name: "Save draft" }).click(); await expect(market.getByText("Listing draft created.")).toBeVisible(); await market.getByRole("button", { name: "Edit" }).click(); await expect(market.getByRole("checkbox").nth(2)).toBeChecked(); await market.getByLabel("Price (minor units)").fill("800"); await market.getByRole("button", { name: "Save draft" }).click(); await expect(market.getByText("Listing draft updated.")).toBeVisible(); await market.getByRole("button", { name: "Submit" }).click(); await expect(market.getByText("Listing submitted for review.")).toBeVisible();

  await page.getByRole("button", { name: /^Live / }).click(); await page.getByRole("button", { name: "Tips, snapshots & goals" }).click(); const commerce = page.getByLabel("Live creator commerce settings"); await expect(commerce.getByLabel("Platform tip catalogue")).toBeVisible(); await expect(commerce.getByRole("button", { name: "Add tip item" })).toHaveCount(0); await commerce.getByRole("button", { name: "Live goals" }).click(); await commerce.getByLabel("Title").fill("Studio goal"); await commerce.getByLabel("Target (EUR)").fill("10.00"); await commerce.getByRole("button", { name: "Create goal" }).click(); await expect(commerce.getByText(/progress comes only/i)).toBeVisible(); await commerce.getByRole("button", { name: "Deactivate goal" }).click(); await commerce.getByRole("button", { name: "Activate goal" }).click(); await commerce.getByRole("button", { name: "Reset from now" }).click(); await expect(commerce.getByText(/prior financial history remains immutable/i)).toBeVisible(); await page.getByRole("button", { name: "Close live setup" }).click();

  const payerContext = await browser.newContext({ permissions: ["camera", "microphone"] }); const payer = await payerContext.newPage(); const payerEmail = `closure-payer-${stamp}@example.com`; await register(payer, payerEmail, password); await payer.goto(`/creator/${username}`); await payer.getByRole("button", { name: "Follow" }).click();
  const invitedContext = await browser.newContext({ permissions: ["camera", "microphone"] }); const invited = await invitedContext.newPage(); const invitedEmail = `closure-invited-${stamp}@example.com`; await register(invited, invitedEmail, password); await invited.goto(`/creator/${username}`); await invited.getByRole("button", { name: "Follow" }).click();
  await payer.setViewportSize({ width: 390, height: 844 }); await payer.reload(); const privateForm = payer.getByLabel("Private session"); await privateForm.getByLabel("Session type").selectOption("two_to_one"); await expect.poll(() => privateForm.getByLabel("Second fan for 2-to-1").locator("option").count(), { timeout: 15_000 }).toBeGreaterThan(1); expect(await overflowingElements(payer)).toEqual([]); await privateForm.getByLabel("Second fan for 2-to-1").selectOption({ index: 1 }); await privateForm.getByRole("button", { name: "Request 2-to-1 session" }).click(); await expect(privateForm.getByText(/creator cannot accept and payment cannot start/i)).toBeVisible();
  await page.reload(); await page.getByRole("button", { name: /^Live / }).click(); await page.getByRole("button", { name: "Private queue" }).click(); await expect(page.getByRole("button", { name: "Waiting for invited fan" })).toBeDisabled(); expect((await api(page, "/live/private-sessions/mine")).body).toEqual([]);
  await invited.goto("/live"); await invited.getByRole("button", { name: "Accept invitation" }).click(); await expect(invited.getByText(/you will never be charged/i)).toBeVisible();
  await page.reload(); await page.getByRole("button", { name: /^Live / }).click(); await page.getByRole("button", { name: "Private queue" }).click(); await page.getByRole("button", { name: "Accept request" }).click(); await expect(page.getByText(/payment authorization is awaiting_payment_authorization/i)).toBeVisible();
  await payer.goto("/live"); await payer.getByRole("button", { name: "Confirm payment authorization" }).click(); await expect(payer.getByText("Payment authorization verified")).toBeVisible(); await expect.poll(async () => (await api(payer, "/live/private-sessions/mine")).body[0]?.status).toBe("ready");
  await page.goto("/live"); await page.getByRole("button", { name: "Join private room" }).click(); await payer.getByRole("button", { name: "Join private room" }).click(); await invited.reload(); await invited.getByRole("button", { name: "Join private room" }).click(); await expect.poll(async () => (await api(payer, "/live/private-sessions/mine")).body[0]?.status, { timeout: 20_000 }).toBe("active");
  await page.getByRole("button", { name: "End private session" }).click(); await invitedContext.close(); await payerContext.close();
});
