"use client";

import { useEffect, useRef, useState } from "react";
import { api, ApiError } from "../../lib/api";

type Group = { id: string; name: string; slug: string; default_creator_basis_points: number };
type Creator = { id: string; creator_id: string; username: string | null; display_name: string | null; status: string; active_contract: { id: string; version: number; creator_basis_points: number; group_basis_points: number; status: string } | null };
type Dashboard = { currency: string; active_creators: number; pending_amount_minor: number; available_amount_minor: number; source_amounts_minor: { ppv: number; subscriptions: number; messaging: number; private_live: number; marketplace: number } };

export default function GroupsPage() {
  const [groups, setGroups] = useState<Group[]>([]); const [selected, setSelected] = useState(""); const [creators, setCreators] = useState<Creator[]>([]); const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [creatorBps, setCreatorBps] = useState<Record<string, string>>({}); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const groupLoadSequence = useRef(0);
  useEffect(() => { api<Group[]>("/groups/mine/managed").then((rows) => { setGroups(rows); setSelected((current) => current || rows[0]?.id || ""); }).catch((e: unknown) => setError(e instanceof ApiError ? e.message : "Unable to load managed groups")); }, []);
  const loadGroup = async (groupId: string) => { if (!groupId) return; const loadSequence = ++groupLoadSequence.current; try { const [memberRows, dashboardRow] = await Promise.all([api<Creator[]>(`/groups/${groupId}/managed-creators`), api<Dashboard>(`/groups/${groupId}/dashboard?currency=EUR`)]); if (loadSequence !== groupLoadSequence.current) return; setCreators(memberRows); setDashboard(dashboardRow); setCreatorBps((current) => { const next = { ...current }; memberRows.forEach((creator) => { if (next[creator.id] === undefined && creator.active_contract) next[creator.id] = String(creator.active_contract.creator_basis_points); }); return next; }); } catch (e) { if (loadSequence !== groupLoadSequence.current) return; setError(e instanceof ApiError ? e.message : "Unable to load group dashboard"); } };
  useEffect(() => { setCreators([]); setDashboard(null); setError(""); void loadGroup(selected); return () => { groupLoadSequence.current += 1; }; }, [selected]);
  const propose = async (creator: Creator) => { const creator_basis_points = Number(creatorBps[creator.id]); if (!Number.isInteger(creator_basis_points) || creator_basis_points < 0 || creator_basis_points > 10_000) { setError("Creator split must be a whole number between 0 and 10000 basis points."); return; } setError(""); setNotice(""); try { await api(`/groups/memberships/${creator.id}/amendments`, { method: "POST", body: JSON.stringify({ creator_basis_points }) }); setNotice("Contract amendment proposed. The creator must explicitly accept it."); await loadGroup(selected); } catch (e) { setError(e instanceof ApiError ? e.message : "Unable to propose contract amendment"); } };
  return <section className="card"><p className="eyebrow">GROUP MANAGER</p><h1>Managed creators</h1><label>Group<select value={selected} onChange={(e) => setSelected(e.target.value)}>{groups.map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</select></label>{dashboard && <section><h2>Ledger dashboard</h2><p>Managed creators: {dashboard.active_creators}</p><p>Pending: {dashboard.pending_amount_minor} {dashboard.currency}</p><p>Available: {dashboard.available_amount_minor} {dashboard.currency}</p><h3>Revenue sources</h3><p>PPV: {dashboard.source_amounts_minor.ppv} {dashboard.currency}</p><p>Subscriptions: {dashboard.source_amounts_minor.subscriptions} {dashboard.currency}</p><p>Messaging: {dashboard.source_amounts_minor.messaging} {dashboard.currency}</p><p>Private live: {dashboard.source_amounts_minor.private_live} {dashboard.currency}</p><p>Marketplace: {dashboard.source_amounts_minor.marketplace} {dashboard.currency}</p></section>}<ul>{creators.map((creator) => <li key={creator.id}><strong>{creator.display_name ?? creator.username ?? creator.creator_id}</strong> — {creator.status} {creator.active_contract && <><p>Contract v{creator.active_contract.version}: creator {creator.active_contract.creator_basis_points / 100}% / group {creator.active_contract.group_basis_points / 100}% ({creator.active_contract.status})</p>{creator.status === "active" && creator.active_contract.status === "active" && <label>Proposed creator split (basis points)<input aria-label={`Proposed creator split for ${creator.display_name ?? creator.username ?? creator.creator_id}`} inputMode="numeric" value={creatorBps[creator.id] ?? ""} onChange={(e) => setCreatorBps((current) => ({ ...current, [creator.id]: e.target.value }))} /><button type="button" onClick={() => void propose(creator)}>Propose amendment</button></label>}</>}</li>)}</ul>{notice && <p role="status">{notice}</p>}{error && <p className="error">{error}</p>}</section>;
}
