"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

import styles from "../../../components/operations-workspace.module.css";
import { ApiError, api } from "../../../lib/api";

type Item = { id: string; status: string; appellant: string; reason: string; action_type: string; content_title: string; case_public_id: string; deadline: string; assigned_to_me: boolean; created_at: string };
type Detail = { id: string; status: string; reason: string; appellant: string; deadline: string; case: { public_id: string; severity: string; status: string }; action: { type: string; date: string; reason: string; target: string }; outcome: string | null; allowed_decisions: string[]; audit: { type: string; created_at: string }[] };

export default function ModeratorAppealsPage() {
  const [items, setItems] = useState<Item[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const pageSize = 25;
  const [status, setStatus] = useState("submitted"); const [actionType, setActionType] = useState(""); const [search, setSearch] = useState(""); const [mine, setMine] = useState(false); const [selected, setSelected] = useState<Detail | null>(null);
  const [outcome, setOutcome] = useState("upheld"); const [reason, setReason] = useState(""); const [confirmed, setConfirmed] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { const params = new URLSearchParams({ page: String(page), page_size: String(pageSize), assigned_to_me: String(mine) }); if (status) params.set("status", status); if (actionType) params.set("action_type", actionType); if (search) params.set("search", search); try { const result = await api<{ items: Item[]; total: number }>(`/trust-safety/appeals/operations?${params}`); setItems(result.items); setTotal(result.total); setError(""); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to load appeals."); } }, [actionType, mine, page, search, status]);
  useEffect(() => { void load(); }, [load]);
  const open = async (id: string) => { try { setSelected(await api<Detail>(`/trust-safety/appeals/operations/${id}`)); setReason(""); setConfirmed(false); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to open appeal."); } };
  const filter = (event: FormEvent) => { event.preventDefault(); setPage(1); void load(); };
  const claim = async () => { if (!selected) return; try { await api(`/trust-safety/appeals/${selected.id}/claim`, { method: "POST" }); setNotice("Appeal assigned to you."); await open(selected.id); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to claim appeal."); } };
  const decide = async () => { if (!selected) return; try { await api(`/trust-safety/appeals/${selected.id}/decision`, { method: "POST", body: JSON.stringify({ outcome, reason }) }); setNotice("Appeal decision recorded and appellant notified."); await open(selected.id); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to decide appeal."); } };
  return <main className={styles.page}><header className={styles.hero}><p className="eyebrow">TRUST &amp; SAFETY OPERATIONS</p><h1>Appeal review</h1><p>Review the original enforcement context and record a reasoned, auditable outcome.</p></header><section className={styles.panel}>
    <form className={styles.filters} onSubmit={filter}><label>Appellant or content<input value={search} onChange={(e) => setSearch(e.target.value)} /></label><label>Status<select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All</option>{["submitted", "under_review", "upheld", "overturned", "partially_overturned"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Enforcement type<select value={actionType} onChange={(e) => setActionType(e.target.value)}><option value="">All</option>{["temporary_containment", "content_remove", "creator_suspend", "marketplace_selling_suspend", "live_terminate"].map((value) => <option key={value}>{value.replaceAll("_", " ")}</option>)}</select></label><label className={styles.confirm}><input checked={mine} onChange={(e) => setMine(e.target.checked)} type="checkbox" /> Assigned to me</label><button>Apply filters</button></form>
    {error && <p className={styles.error} role="alert">{error}</p>}{notice && <p className={styles.notice} role="status">{notice}</p>}<div className={styles.split}><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Appeal</th><th>Action</th><th>Status</th><th>Deadline</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><button className={styles.rowButton} onClick={() => void open(item.id)}><strong>{item.appellant}</strong><span>{item.content_title} · {item.case_public_id}</span></button></td><td>{item.action_type.replaceAll("_", " ")}</td><td><span className={styles.status}>{item.status.replaceAll("_", " ")}</span></td><td>{new Date(item.deadline).toLocaleString()}</td></tr>)}</tbody></table>{!items.length && <p className={styles.empty}>No appeals match these filters.</p>}<div className={styles.pagination}><button disabled={page === 1} onClick={() => setPage((v) => v - 1)}>Previous</button><span>Page {page}</span><button disabled={page * pageSize >= total} onClick={() => setPage((v) => v + 1)}>Next</button></div></div>
      <aside className={`${styles.panel} ${styles.detail}`}>{selected ? <><div className={styles.detailHeader}><div><p className="eyebrow">{selected.case.public_id}</p><h2>{selected.action.target}</h2></div><span className={styles.status}>{selected.status}</span></div><dl className={styles.facts}><div><dt>Appellant</dt><dd>{selected.appellant}</dd></div><div><dt>Enforcement</dt><dd>{selected.action.type.replaceAll("_", " ")}</dd></div><div><dt>Severity</dt><dd>{selected.case.severity}</dd></div><div><dt>Deadline</dt><dd>{new Date(selected.deadline).toLocaleString()}</dd></div></dl><h3>Appellant statement</h3><p>{selected.reason}</p><h3>Original reason</h3><p>{selected.action.reason}</p>{selected.allowed_decisions.length > 0 && <div className={styles.decision}><button className={styles.secondary} onClick={() => void claim()}>Assign to me</button><label>Outcome<select value={outcome} onChange={(e) => setOutcome(e.target.value)}>{selected.allowed_decisions.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></label><label>Decision reason<textarea value={reason} onChange={(e) => setReason(e.target.value)} /></label><label className={styles.confirm}><input checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} type="checkbox" /> I confirm this outcome.</label><button disabled={!confirmed || reason.trim().length < 1} onClick={() => void decide()}>Record decision</button></div>}<h3>Audit history</h3><ul className={styles.timeline}>{selected.audit.map((event, index) => <li key={`${event.type}-${index}`}>{event.type}<small>{new Date(event.created_at).toLocaleString()}</small></li>)}</ul></> : <p className={styles.empty}>Select an appeal to review it.</p>}</aside>
    </div></section></main>;
}
