import sqlalchemy as sa

from alembic import op

"""content media foundation"""

revision = "350b070c3fd5"
down_revision = "20260819_0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_items",
        sa.Column("owner_creator_id", sa.UUID(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("content_type", sa.Enum("gallery", "video", name="content_type"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "processing",
                "pending_review",
                "published",
                "archived",
                "rejected",
                "removed",
                name="content_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "moderation_status",
            sa.Enum(
                "not_reviewed",
                "queued",
                "approved",
                "flagged",
                "rejected",
                "removed",
                name="moderation_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "access_policy",
            sa.Enum("free", "followers", "subscription", "ppv", "private", name="access_policy"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_content_items_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_creator_id"],
            ["creator_profiles.id"],
            name=op.f("fk_content_items_owner_creator_id_creator_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_items")),
    )
    op.create_index(
        op.f("ix_content_items_access_policy"), "content_items", ["access_policy"], unique=False
    )
    op.create_index(
        op.f("ix_content_items_content_type"), "content_items", ["content_type"], unique=False
    )
    op.create_index(
        op.f("ix_content_items_created_by_user_id"),
        "content_items",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_items_moderation_status"),
        "content_items",
        ["moderation_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_items_owner_creator_id"),
        "content_items",
        ["owner_creator_id"],
        unique=False,
    )
    op.create_index(op.f("ix_content_items_status"), "content_items", ["status"], unique=False)
    op.create_table(
        "media_assets",
        sa.Column("owner_creator_id", sa.UUID(), nullable=False),
        sa.Column("media_type", sa.Enum("image", "video", name="media_type"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending_upload",
                "uploaded",
                "queued",
                "processing",
                "ready",
                "failed",
                "rejected",
                "archived",
                name="media_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "moderation_status",
            sa.Enum(
                "not_reviewed",
                "queued",
                "approved",
                "flagged",
                "rejected",
                "removed",
                name="moderation_status",
            ),
            nullable=False,
        ),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=127), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("processing_error", sa.String(length=255), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_creator_id"],
            ["creator_profiles.id"],
            name=op.f("fk_media_assets_owner_creator_id_creator_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_media_assets_storage_key")),
    )
    op.create_index(
        op.f("ix_media_assets_checksum_sha256"), "media_assets", ["checksum_sha256"], unique=False
    )
    op.create_index(
        op.f("ix_media_assets_media_type"), "media_assets", ["media_type"], unique=False
    )
    op.create_index(
        op.f("ix_media_assets_moderation_status"),
        "media_assets",
        ["moderation_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_assets_owner_creator_id"), "media_assets", ["owner_creator_id"], unique=False
    )
    op.create_index(op.f("ix_media_assets_status"), "media_assets", ["status"], unique=False)
    op.create_table(
        "content_entitlements",
        sa.Column("subject_user_id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("source_reference", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "revoked", "expired", name="entitlement_status"),
            nullable=False,
        ),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content_items.id"],
            name=op.f("fk_content_entitlements_content_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_user_id"],
            ["users.id"],
            name=op.f("fk_content_entitlements_subject_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_entitlements")),
    )
    op.create_index(
        op.f("ix_content_entitlements_content_id"),
        "content_entitlements",
        ["content_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_entitlements_status"), "content_entitlements", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_content_entitlements_subject_user_id"),
        "content_entitlements",
        ["subject_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_entitlements_valid_until"),
        "content_entitlements",
        ["valid_until"],
        unique=False,
    )
    op.create_table(
        "content_performers",
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("creator_profile_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content_items.id"],
            name=op.f("fk_content_performers_content_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["creator_profile_id"],
            ["creator_profiles.id"],
            name=op.f("fk_content_performers_creator_profile_id_creator_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "content_id", "creator_profile_id", name=op.f("pk_content_performers")
        ),
    )
    op.create_table(
        "galleries",
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("cover_media_asset_id", sa.UUID(), nullable=True),
        sa.Column("preview_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content_items.id"],
            name=op.f("fk_galleries_content_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["cover_media_asset_id"],
            ["media_assets.id"],
            name=op.f("fk_galleries_cover_media_asset_id_media_assets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_galleries")),
        sa.UniqueConstraint("content_id", name=op.f("uq_galleries_content_id")),
    )
    op.create_table(
        "media_derivatives",
        sa.Column("media_asset_id", sa.UUID(), nullable=False),
        sa.Column(
            "derivative_type",
            sa.Enum(
                "thumbnail",
                "display",
                "blurred_preview",
                "poster",
                "preview_clip",
                "playback",
                name="derivative_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending_upload",
                "uploaded",
                "queued",
                "processing",
                "ready",
                "failed",
                "rejected",
                "archived",
                name="media_status",
            ),
            nullable=False,
        ),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("mime_type", sa.String(length=127), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["media_asset_id"],
            ["media_assets.id"],
            name=op.f("fk_media_derivatives_media_asset_id_media_assets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_derivatives")),
        sa.UniqueConstraint(
            "media_asset_id", "derivative_type", name=op.f("uq_media_derivatives_media_asset_id")
        ),
        sa.UniqueConstraint("storage_key", name=op.f("uq_media_derivatives_storage_key")),
    )
    op.create_index(
        op.f("ix_media_derivatives_media_asset_id"),
        "media_derivatives",
        ["media_asset_id"],
        unique=False,
    )
    op.create_table(
        "video_contents",
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("source_media_asset_id", sa.UUID(), nullable=False),
        sa.Column("preview_start_seconds", sa.Integer(), nullable=False),
        sa.Column("preview_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content_items.id"],
            name=op.f("fk_video_contents_content_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_media_asset_id"],
            ["media_assets.id"],
            name=op.f("fk_video_contents_source_media_asset_id_media_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_contents")),
        sa.UniqueConstraint("content_id", name=op.f("uq_video_contents_content_id")),
        sa.UniqueConstraint(
            "source_media_asset_id", name=op.f("uq_video_contents_source_media_asset_id")
        ),
    )
    op.create_table(
        "gallery_items",
        sa.Column("gallery_id", sa.UUID(), nullable=False),
        sa.Column("media_asset_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_preview", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["gallery_id"],
            ["galleries.id"],
            name=op.f("fk_gallery_items_gallery_id_galleries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["media_asset_id"],
            ["media_assets.id"],
            name=op.f("fk_gallery_items_media_asset_id_media_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gallery_items")),
        sa.UniqueConstraint("gallery_id", "media_asset_id", name="uq_gallery_items_gallery_asset"),
        sa.UniqueConstraint("gallery_id", "position", name="uq_gallery_items_gallery_position"),
    )
    op.create_index(
        op.f("ix_gallery_items_gallery_id"), "gallery_items", ["gallery_id"], unique=False
    )
    op.create_index(
        op.f("ix_gallery_items_media_asset_id"), "gallery_items", ["media_asset_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gallery_items_media_asset_id"), table_name="gallery_items")
    op.drop_index(op.f("ix_gallery_items_gallery_id"), table_name="gallery_items")
    op.drop_table("gallery_items")
    op.drop_table("video_contents")
    op.drop_index(op.f("ix_media_derivatives_media_asset_id"), table_name="media_derivatives")
    op.drop_table("media_derivatives")
    op.drop_table("galleries")
    op.drop_table("content_performers")
    op.drop_index(op.f("ix_content_entitlements_valid_until"), table_name="content_entitlements")
    op.drop_index(
        op.f("ix_content_entitlements_subject_user_id"), table_name="content_entitlements"
    )
    op.drop_index(op.f("ix_content_entitlements_status"), table_name="content_entitlements")
    op.drop_index(op.f("ix_content_entitlements_content_id"), table_name="content_entitlements")
    op.drop_table("content_entitlements")
    op.drop_index(op.f("ix_media_assets_status"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_owner_creator_id"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_moderation_status"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_media_type"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_checksum_sha256"), table_name="media_assets")
    op.drop_table("media_assets")
    op.drop_index(op.f("ix_content_items_status"), table_name="content_items")
    op.drop_index(op.f("ix_content_items_owner_creator_id"), table_name="content_items")
    op.drop_index(op.f("ix_content_items_moderation_status"), table_name="content_items")
    op.drop_index(op.f("ix_content_items_created_by_user_id"), table_name="content_items")
    op.drop_index(op.f("ix_content_items_content_type"), table_name="content_items")
    op.drop_index(op.f("ix_content_items_access_policy"), table_name="content_items")
    op.drop_table("content_items")
    # ### end Alembic commands ###
