"use client";

import { useCallback, useEffect, useState } from "react";

import styles from "../../../components/operations-workspace.module.css";
import { ApiError, api } from "../../../lib/api";

type Context = { creator: { display_name: string; username: string }; contents: { id: string; title: string; type: string; requires_consent: boolean }[]; performers: { id: string; label: string; country_code: string }[]; releases: { id: string; status: string; release_type: string; participant: string; contents: { id: string; title: string }[]; created_at: string; effective_until: string | null; revoked_at: string | null }[] };

export default function CreatorConsentPage() {
  const [context, setContext] = useState<Context | null>(null); const [contentId, setContentId] = useState(""); const [performer, setPerformer] = useState(""); const [evidence, setEvidence] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { try { const result = await api<Context>("/trust-safety/consent/context"); setContext(result); setContentId((value) => value || result.contents[0]?.id || ""); setPerformer((value) => value || result.performers[0]?.label || ""); setError(""); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to load consent context."); } }, []);
  useEffect(() => { void load(); }, [load]);
  const submit = async () => { try { await api("/trust-safety/consent/releases", { method: "POST", body: JSON.stringify({ release_type: "co_performer_release", participant_reference: performer, content_ids: [contentId], evidence_reference: evidence || null }) }); setNotice("Release submitted for independent review."); setEvidence(""); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to submit release."); } };
  const revoke = async (id: string) => { if (!window.confirm("Revoke this verified release? The historical record will remain.")) return; try { await api(`/trust-safety/consent-releases/${id}/revoke`, { method: "POST" }); setNotice("Release revoked; its history remains available."); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to revoke release."); } };
  return <main className={styles.page}><header className={styles.hero}><p className="eyebrow">CREATOR STUDIO</p><h1>Consent releases</h1><p>Select from your own content and registered performers. Review authority stays with Trust &amp; Safety.</p></header><section className={styles.panel}>{error && <p className={styles.error} role="alert">{error}</p>}{notice && <p className={styles.notice} role="status">{notice}</p>}
    <div className={styles.decision}><h2>Submit a release</h2><label>Content<select value={contentId} onChange={(e) => setContentId(e.target.value)}>{context?.contents.map((content) => <option key={content.id} value={content.id}>{content.title} · {content.type}</option>)}</select></label><label>Participant / performer<select value={performer} onChange={(e) => setPerformer(e.target.value)}>{context?.performers.map((item) => <option key={item.id} value={item.label}>{item.label} · {item.country_code}</option>)}</select></label><label>Evidence reference (optional)<input value={evidence} onChange={(e) => setEvidence(e.target.value)} /></label><button disabled={!contentId || !performer} onClick={() => void submit()}>Submit for review</button>{context && !context.performers.length && <p className={styles.empty}>Register an eligible performer before submitting a co-performer release.</p>}</div>
    <h2>Release history</h2><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Participant</th><th>Content</th><th>Status</th><th>Submitted</th><th>Action</th></tr></thead><tbody>{context?.releases.map((release) => <tr key={release.id}><td>{release.participant}</td><td>{release.contents.map((content) => content.title).join(", ")}</td><td><span className={styles.status}>{release.status}</span></td><td>{new Date(release.created_at).toLocaleString()}</td><td>{release.status === "verified" && <button aria-label={`Revoke release for ${release.participant}`} className={styles.secondary} onClick={() => void revoke(release.id)}>Revoke</button>}</td></tr>)}</tbody></table>{context && !context.releases.length && <p className={styles.empty}>No release history yet.</p>}</div>
  </section></main>;
}
